### ISSUE TITLE
.ppt file attachments fail validation

### ISSUE THREAD

**Issue by lazylester** [ophrescue/RescueRails#1005]
MimeMagic is used by Paperclip to detect file content type.

MimeMagic declares .ppt files to be 'application/x-ole-storage'. Actually I can't say for sure that it mis-identifies _all_ .ppt files, just the one I tried, which might quite possibly have been produced by Keynote or Google docs.

The MimeMagic issues list also mentions mis-identified .xls and .docx files, too. We seem to be OK with these, but there could be special cases, depending on the sources of these files (e.g. Google docs)

Since Paperclip is no longer being maintained, and possibly MimeMagic too. There are a number of hacks to work around this (see MimeMagic issues). 

So, logging this known issue here, although it apparently has not been reported by users. As an alternative to the workarounds, migration to ActiveStorage may be indicated.

**Comment by markottaviani** [comment]
mime checks were turned off due to issues w/ some uploads, issues w/ the File Upload/Download processes and Mime detection and ActiveStorage are being covered in #1537
