### ISSUE TITLE
Upload error reasons not shown when uploading dog photos

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#1015]
![missing-errors](https://user-images.githubusercontent.com/793671/46985062-7926a080-d0b6-11e8-9d97-ba346c52302e.png)

**Comment by lazylester** [comment]
@markottaviani is it possible to see the production log for the time when this upload was rejected to see what was reported (if anything) on the server?

**Comment by lazylester** [comment]
I got the production log snippet... it's a log of a Dogs::ManagerController#update action, and it completes with "Completed 200 OK".

Are you saying that this was you attempting to upload the .docx document and you got a flash error message "form could not be saved see errors below"?

**Comment by markottaviani** [comment]
Correct.

**Comment by markottaviani** [comment]
Also, with respect to the error report about uploading images, it turns out the image in question was 13MB.  The limit is 10MB.  So users are getting a generic error message like in the screenshot at the top of this issue, but aren't getting a message that states that the file is too big.

**Comment by lazylester** [comment]
That should be an easy fix, the file size is detectable in the browser. I'm looking out for reporting of the symptoms of issue#1005, which may arise for .docx files of some particular provenance.
