### ISSUE TITLE
Add Volunteer Application to System

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#141]
Addition of Foster and possibly general volunteer applications to the system, these are currently handled via an email form.   Still working on collecting the high level concept from the Volunteer/Foster Coordinators.

Biz Contacts:
* Beth H. 
* Laurie
* Jen

**Comment by markottaviani** [comment]
Biz putting together initial drafts of intake forms.  Feedback expected in 1-2 weeks.

**Comment by TheDudeWithTheThing** [comment]
Any updates here?

**Comment by markottaviani** [comment]
haha nope.  Doing some high level planning this week with them.  Key outcome will be some primary points of contact for the specific things they care about so they keep moving.
