### ISSUE TITLE
Handle second email address for adopters

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#1536]
Adoption Coordinators that add a 2nd email address to the email value for an adoption application will cause automated emails and mailchimp subscriptions to not work correctly.

Suggested fix, add an Adoption Coordinator only field for  a 2nd email address.

Add validation rules to make sure it's impossible for AC's to add a 2nd email address to the email column.

**Comment by kateugenio** [comment]
A few questions:

1. ..."_that add a 2nd email address to the email value_..", to clarify, is this if they click Edit and type in another email address in the input field? Example, if the original email value is `test1@test.com`, would they type something like: `test1@test.com, test2@test.com` in the field?

2. Is there a reason why the AC would need to update the applicant's email?

3. Just so I understand, why do AC's put in a 2nd email address? Is this a backup email for the applicant? Will it be used for as part of the automated emails?

Thanks!

**Comment by markottaviani** [comment]
Great questions, thanks!

1. Yes that is the 'bad' behavior that the validation should check, catch and reject from the Adopter show Show page.

2. Yes, applications sometime mistype their email address or an applicant has decided they want to use a different email address, etc. 

3. The 2nd email address is often a spouse or other family member, really it acts as a backup or alternative contact.  So with that in mind, the 2nd email address _doesn't_ need any of the transactional emails or a mailchimp subscription.  However it should still work in the adopter search.   So if someone from the rescue gets an email from that person out of the blue a year from now, the volunteer can quickly search using the email address and hopefully find the right records!
