### ISSUE TITLE
Upgrade banned_adopters to Bootstrap 4

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#1567]
Upgrade all views for `banned_adopters` to use Bootstrap 4, also provide a cleaner User Experience since it's fairly gross.

**Comment by ahutnick** [comment]
Ok, Bootstrap upgrade done - wanted to check in on which User Experience updates to implement. I have ideas (i.e. adding sortable columns for name and location / making the edit process more like adopters), but I wanted to make sure I was on the right track first.
