### ISSUE TITLE
Adopter Pagination and Assignee sorting results in the same record showign up on multiple pages

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#1571]
Adoption Coordinator is trying to find their assigned applications, but when sorting to find their assignments, the same records can show up on different pages.  

Given how the pagination queries work, this is probably to be expected:

![dupe-records-on-sort](https://user-images.githubusercontent.com/793671/85227358-00a7d500-b3ab-11ea-9761-d65320b7b4c6.png)

Best solution would be to *finally* enable the feature that allows folks to filter to only view their own assigned applications.

**Comment by danisaurio** [comment]
@markottaviani isn't this one solved on #1585 ?

**Comment by markottaviani** [comment]
Yes
