### ISSUE TITLE
User should be able to filter by applications assigned to themselves

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#1584]
These buttons have been here forever, but have never actually worked.  
![Capture](https://user-images.githubusercontent.com/793671/86072272-39047e80-ba4f-11ea-8e76-75556c887a50.PNG)

Clicking "My Apps" should only show applications that are assigned to the logged in Users
Clicking "Open Apps" should only show applications that are unassigned
Clicking "All Apps" will result in the existing behavior (all apps!)

**Comment by markottaviani** [comment]
Adding this feature will also close out the need to deal with the bug reported in #1571

**Comment by markottaviani** [comment]
@danisaurio okay I'm 100% certain this hasn't been done yet!

**Comment by danisaurio** [comment]
@markottaviani great! I'm on it :)
