### ISSUE TITLE
Full Text Searching across all data

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#192]
Ability to search all DMS Content a user has access to.  Fully Indexed Global Search, dogs, comments, etc.  

Existing search is pretty rough and low-tech.  

Assess Sunspot and other ruby search solutions for improving searching through OPH records.

http://railscasts.com/episodes/278-search-with-sunspot

**Comment by docvego** [comment]
Is there anyway to or could it be added to the task list to search dogs by their micro chip numbers?

We had a call today about a found dog that was one of ours and it would have taken me forever to find him if I hadn't posted on Facebook and the foster knew who it was.

**Comment by TheDudeWithTheThing** [comment]
do we have that data available?

**Comment by docvego** [comment]
Yeah, dog.microchip

**Comment by TheDudeWithTheThing** [comment]
oh man this thing is over a year old

**Comment by TheDudeWithTheThing** [comment]
do we make the commitment to elastic search?  that's more cost to OPH

**Comment by markottaviani** [comment]
No commitment to anything we can use whatever we want.

**Comment by TheDudeWithTheThing** [comment]
sorry commitment is the wrong word, do we make the jump? Time to take `DogSearcher` for his last walk?

**Comment by TheDudeWithTheThing** [comment]
I can bang this out in 30min vs 1 week for moving search to something else

**Comment by markottaviani** [comment]
Certainly a fan of getting this done nice and easy, what would we be dealing with $$$ wise for a move to Elastic?

**Comment by TheDudeWithTheThing** [comment]
cost!
https://aws.amazon.com/elasticsearch-service/pricing/

**Comment by markottaviani** [comment]
@TheDudeWithTheThing I'll talk to the OPH Folks about cost next week on this to get a solid gauge on interest.  

t2.micro.elasticsearch    - staging
t2.small.elasticsearch    - production

Honestly even two micros might be enough.      ~$40 /month on the high side

**Comment by TheDudeWithTheThing** [comment]
What's the usage of the current search?

**Comment by markottaviani** [comment]
Honestly not much.  Only users of the search are OPH Staff/Volunteers.

**Comment by markottaviani** [comment]
Also a possible option https://www.viget.com/articles/implementing-full-text-search-in-rails-with-postgres

**Comment by markottaviani** [comment]
not going to do this one
