### ISSUE TITLE
Enhance Dog Photo Upload Experience

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#242]
Deal with larger photos better, avoid system timeouts,.

https://www.facebook.com/groups/348416295253712/permalink/1525830774178919/
_Is there a way for the latest dog picture to default to the top unless rearranged? For example, if I upload a picture it goes to the top unless I change it._

**Comment by lazylester** [comment]
I know that this issue is old, but I'm coming across it again while optimizing the manager view and gallery pages for mobile. The photo sizes are unnecessarily huge and we really should be reducing the size when they're uploaded. Rails 5.2 now has this built in!

**Comment by TheDudeWithTheThing** [comment]
oh man 2014, ha

**Comment by markottaviani** [comment]
A github never forgets.
