### ISSUE TITLE
Upgrade to Rails 4

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#256]
Bootstrap upgrade is very ugly on Rails 3.2.x

Time to finally upgrade to Rails 4.1

**Comment by markottaviani** [comment]
http://technology.customink.com/blog/2014/09/16/from-rails-3.2-to-4.2/

**Comment by markottaviani** [comment]
Breaking out the move to Strong_Parameters as a separate effort and tackling that first.

**Comment by markottaviani** [comment]
finally done with strong params!

**Comment by TheDudeWithTheThing** [comment]
huge!  am I supposed to be doing anything?  baby #2 on the way, work is crazy, holidays, I can't keep track!

**Comment by markottaviani** [comment]
No worries, right now not worth doing anything big until the rails 4 stuff is done.  

Any tips on rewriting the ActiveRecord stuff in the models would be helpful.

**Comment by markottaviani** [comment]
DONE!

**Comment by TheDudeWithTheThing** [comment]
haha that was way easier than it should have been, HUGE!

**Comment by markottaviani** [comment]
Super huge, couldn't have done it without you, thanks dude!

**Comment by TheDudeWithTheThing** [comment]
You bet, dogs #1!
