### ISSUE TITLE
Foster Filtering

### ISSUE THREAD

**Issue by docvego** [ophrescue/RescueRails#314]
From the Foster's Tab of the Staff Directory (aka User Index)

A user should be able to filter the list of fosters by any or none following criteria:

state  :string   (Type in the state abbrv.)

available_to_foster    :boolean
agreement_id           :integer   (if present or not)
house_type             :string(40)   (own/rent)
breed_restriction      :boolean
weight_restriction     :boolean
has_own_dogs           :boolean
has_own_cats           :boolean
children_under_five    :boolean
has_fenced_yard        :boolean
can_foster_puppies     :boolean
parvo_house            :boolean

**Comment by docvego** [comment]
Alright.  I have idea how to design this interface.  Originally I was thinking https://moqups.com/#!/edit/docvego/5GMDBWMN

However, I realized I need to filter where true, false or the ability to ignore one of the booleans.  Maybe something more like the 'Reward Type' and 'Specialty' things here?

http://quince.infragistics.com/Patterns/Examples/6b246179-a885-4186-bbbc-afdcb3e096f7-active-filtering-mint.jpg

**Comment by TheDudeWithTheThing** [comment]
I'm on it!

**Comment by docvego** [comment]
Updated https://moqups.com/#!/edit/docvego/5GMDBWMN with another idea for what the filters might need to look like (Yes/No/Any) as opposed to checkboxes
