### ISSUE TITLE
Unable to Link Dogs

### ISSUE THREAD

**Issue by docvego** [ophrescue/RescueRails#354]
Defect verified, and probably introduced in last night's release somehow.   

Linking dogs to Adoption Applications doesn't work correctly.

**Comment by TheDudeWithTheThing** [comment]
maybe we give up on caching until we can really dig in OR include it as part of the upgrade to rails 4, etc...

I don't get how it cached blank pages

**Comment by docvego** [comment]
Oh snap, I totally missed that you wrapped the adopters show page in a cache.  At least this is a easy fix.

**Comment by TheDudeWithTheThing** [comment]
any clue why it's broken though?  did I miss an admin section or something?

**Comment by docvego** [comment]
My guess would be that the dog linking thing happens inline dynamically and doesn't cause the cache to refresh or something like that.
