### ISSUE TITLE
Implement a Client side MVC Framework (Ember?)

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#355]

**Comment by TheDudeWithTheThing** [comment]
20min tops

any real reason to go with angular?  I only ask since it's the only 1 of the big 3 I haven't used.

**Comment by docvego** [comment]
Nope!  I've never used any of the big three at all, that was just the one that you had mentioned the most I thought.

**Comment by docvego** [comment]
Also, I just set us up on https://waffle.io/ophrescue/RescueRails so we can have a nice little Kanban board

**Comment by TheDudeWithTheThing** [comment]
intense!

Ember is the one I've used most / use at work / am most comfortable with. Backbone I think is pretty similar to when I used it last, which was a while ago.
