### ISSUE TITLE
Filters and search for Public Dog Gallery

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#357]
When viewing the Dog / Cat Gallery allow for the following filter options:
* Age
* Size
* Gender

**Comment by TheDudeWithTheThing** [comment]
@markottaviani just to confirm, this is in the non manager view right?

**Comment by markottaviani** [comment]
Yup!

**Comment by markottaviani** [comment]
May use what comes out of #594 here

**Comment by lazylester** [comment]
I'll do this in conjunction with the work I'm doing on the manager-view. This includes Bootstrap 4.1 (as the first page to use this upgrade, others to follow), and mobile-optimized manager-view and gallery-view.
