### ISSUE TITLE
Strip whitespace for applicant emails

### ISSUE THREAD

**Issue by docvego** [ophrescue/RescueRails#358]
Adoption Application will throw jquery error if the user puts spaces before or after the email address.   Ensure users can have leading or trailing spaces in the email box, and still submit an application.   As per current spec, if an e-mail address was already used for an application, jquery validate throws an error message.  

Possible solution:
http://stackoverflow.com/questions/1827483/jquery-validate-plugin-how-to-trim-values-before-form-validation

**Comment by TheDudeWithTheThing** [comment]
did you confirm in logs somewhere that this is what was happening?  who puts spaces in?  maybe a paste job or something

**Comment by docvego** [comment]
Wouldn't show up in logs since it would get blocked by jquery validate
on the client side.

I'm sure we have applicants that wouldn't be able to figure that kind
of a problem out.

It's still probably worth doing a sweep with mobile browsers via browserstack.

**Comment by docvego** [comment]
Checked a few droid phones on browserstack and didn't see any issues other than the whitespace stuff.

**Comment by docvego** [comment]
> Galaxy s5 
>The 1st time..  I started typing and it "showed up" as an option to choose since it was something I had >typed many times before. 
>Then I typed it in completely. Neither worked.
