### ISSUE TITLE
Location based Volunteer Search

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#391]
*I was wondering if something can be done to make it easier to identify what city each volunteer lives in. Maybe make the Location tab clickable? When it is clicked the volunteers cities will be alphabetized? This would help when trying to find volunteers in a certain location.*   - OPH Staff

I think our address data is in pretty good shape for everyone in the user field.  If we could do geolocation that would be awesome sauce.  

As a user I navigate to the */users page. 
I then enter a City,State or Zip and hit a search button
A list of volunteers is returned ranked by distance and the number of miles away is shown.

Bonus Points/Phase 2,
Have this work in cooperation with the Foster Filters/Foster tab /users?foster=true

**Comment by TheDudeWithTheThing** [comment]
I can take a swing at this one. I'm not sure what defines a volunteer though.

**Comment by markottaviani** [comment]
Basically everyone that exists in the User model.

**Comment by TheDudeWithTheThing** [comment]
Well that's easy enough

**Comment by markottaviani** [comment]
Word, updated the description a bit

**Comment by markottaviani** [comment]
Okay, looks like this is next on deck.  Any thoughts on a gem to use to support this?
