### ISSUE TITLE
Generic Pre and Post Dog Bios

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#403]
Add Option to Admin Screens to have 'Boilerplate' information that appears before or after all  dogs' bios.

**Comment by TheDudeWithTheThing** [comment]
Oh hi! Feel free to assign me stuff

**Comment by markottaviani** [comment]
Howdy!  Here is some stuff to muck with.

**Comment by markottaviani** [comment]
I'll fwd you an email chain on this too

**Comment by TheDudeWithTheThing** [comment]
I'm not sure I understand what the actual boilerplate text is, and we'll want a button / checkbox for users to hit to append it to the bio?

**Comment by markottaviani** [comment]
This just got sunk down the backlog, but I think what we want to do is have some kind of a 'config' screen that admins can get to where they can add/edit text.  And then have that text show up above or below a dog's description.

**Comment by markottaviani** [comment]
cancelling
