### ISSUE TITLE
Restrictions to Staff Resources

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#404]

**Comment by markottaviani** [comment]
"Thinking two levels.  One is basic access.  Second is elevated access.  

We need a lot of folks who run events and do grants and admin to have access to a lot of info.  But for regular volunteers it is nice for them to have access to training materials and marketing materials but not necessarily the business type stuff. "

**Comment by markottaviani** [comment]
In short, need an extra privilege level for the Staff Resources section.

**Comment by markottaviani** [comment]
Sanity of OPH Admin
Need to protect proprietary information

**Comment by TheDudeWithTheThing** [comment]
with the upgrade to rails 4 might be time to use Pundit or CanCanCan

https://github.com/elabs/pundit
https://github.com/CanCanCommunity/cancancan

**Comment by markottaviani** [comment]
Me Gusta, the permission system could totally use a rebuild.
