### ISSUE TITLE
Paginate Dog Views

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#406]

**Comment by markottaviani** [comment]
Some dog index views are not paginated and this murders the database.  Fix this crap quick.

**Comment by TheDudeWithTheThing** [comment]
how many dog index views are there?

**Comment by markottaviani** [comment]
scratch that, dogs are actually paginated.  The adopters index isn't, but I'm going to not screw with that for now.  Mess around with caching and hows those pages get displayed after we upgrade rails and el bootstrap.
