### ISSUE TITLE
Medical Notes Section

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#407]
*Section in the dog profiles where we can have high level summary of medical concerns/holds/addendums needed.  Right now – when medical makes notes, they get lost in with the rest of the notes.  We need to ensure they are somehow called out.  I picture a medical box with text.  Maybe it stays at the top of a notes section – maybe it’s on the right hand side?  But we need to ensure the medical summary for each dog is not getting lost in with general personality and adoption notes.*

* Adopter satisfaction
* Ease of access to very important info for adoption coordinators
* Check for adoption coordinators at events

**Comment by TheDudeWithTheThing** [comment]
Is this all?

![](https://www.evernote.com/l/AFtORN35RWtHYI40zFXOyIIQ4nAjR0QgCAMB/image.png)

**Comment by markottaviani** [comment]
As far as the edit screen, pretty much.   How about we change it to "Medical Summary" and move it below Public Description on the edit screen.

**Comment by markottaviani** [comment]
![medical](https://cloud.githubusercontent.com/assets/793671/9833030/5ea2482e-5957-11e5-829c-be3a6eb777b4.png)

I'm thinking have the Medical Summary show up here, and viewing should be restricted the same as the comments are (not viewable to the public).

**Comment by TheDudeWithTheThing** [comment]
:+1:

**Comment by TheDudeWithTheThing** [comment]
look at that nice horizontal rule

![](https://www.evernote.com/l/AFtaIXQK2hBLAJvswWMtgvgO1IyQ-GPrgsUB/image.png)

**Comment by markottaviani** [comment]
hahaha A++++

**Comment by markottaviani** [comment]
Implemented in Prod
