### ISSUE TITLE
Rebuild Authorizations

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#411]
Refactor into a proper permission system to better manage user permissions.

**Comment by markottaviani** [comment]
https://github.com/elabs/pundit
https://github.com/CanCanCommunity/cancancan

**Comment by TheDudeWithTheThing** [comment]
nice, thredded just moved to pundit so wanted an excuse to play with it

**Comment by markottaviani** [comment]
Cool, let me know before you dive into this one.  It's probably worth talking to the Business and figuring out what the proper business roles are these days.

**Comment by TheDudeWithTheThing** [comment]
#446 is a duplicate of this no?

**Comment by markottaviani** [comment]
Nope, updated the description.  This is Authorization, the other is Authentication.

**Comment by markottaviani** [comment]
Stuff to check out: 

rolify and cancancan — Rolify allows the application to assign roles such as User or Admin on a User object. Then CanCanCan allows you to take those roles and apply authorization policies.
