### ISSUE TITLE
Invalid Sort Method for Feed Syncs

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#423]
This sort! is now an undefined method.

https://github.com/ophrescue/RescueRails/blob/master/lib/tasks/adoptapet_sync.rake#L38

and here

https://github.com/ophrescue/RescueRails/blob/master/lib/tasks/petfinder_sync.rake#L60

I think because the model has the sort on photos already built in 
https://github.com/ophrescue/RescueRails/blob/master/app/models/dog.rb#L62

We can just delete the line of code in each rake task that calls the sort! 

Sound right?

**Comment by TheDudeWithTheThing** [comment]
yeah, use the AR order instead

`d.photos.visible.order('updated_at desc')`
