### ISSUE TITLE
Move to SendGrid Web API

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#432]
Modify existing transactional emails to use SendGrid Web API + Active Job.

**Comment by TheDudeWithTheThing** [comment]
replacing mailchimp??

**Comment by markottaviani** [comment]
haha no way.  This is for transactional emails.  We're already using Sendgrid for the "Thanks for Filling out an Adoption Application" email and a notification email that goes to the adoption team.  

 Idea is to build out notification stuff, let people know when their application hits a specific statuses.  

From there I'm thinking a move to support email intake as well.  Right now adoption coordinators spend a lot of time copy/pasting emails into the comments section.

**Comment by markottaviani** [comment]
Looks like they had some recent updates too https://sendgrid.com/blog/introducing-v3mailsend-sendgrids-new-mail-endpoint

**Comment by markottaviani** [comment]
cancelling
