### ISSUE TITLE
Upgrade AWS SDK

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#433]
AWS SDK2.0 is out, paperclip 5.0 will require it, and the 4.x now supports it.  

Getting paperclip to work with AWS SDK seems fairly easy, however I had a terrible time trying to rewrite the download_url method in the Attachment model.  

@TheDudeWithTheThing any interest in taking this on?

**Comment by TheDudeWithTheThing** [comment]
Will have a look!

**Comment by TheDudeWithTheThing** [comment]
I can't even get AWS to be configured, it's not recognizing the region I'm setting, awful

**Comment by markottaviani** [comment]
Gross, I think we  have a test region you can try will be able to check tomorrow.

**Comment by TheDudeWithTheThing** [comment]
K I'm dumb and was editing the wrong file  (attachements.rb vs. photos.rb)

All good now, just need to configure paths to match the old paths then I think everything, including the file download, will work.
