### ISSUE TITLE
Rebuild Authentication Using Devise or Similar Library

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#446]
The current Authentication System, passwords, hashing, etc. was built by hand.  It probably leave a lot to be desired in terms of checking password complexity, logging in from different IPs, and other sorts of authentication stuff.

**Comment by TheDudeWithTheThing** [comment]
I thought I put this already, but we should check out Pundit for this

**Comment by markottaviani** [comment]
Duplicate, replaced by #580
