### ISSUE TITLE
Endless Scrolling

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#447]
Implement endless scrolling for Users, Dogs and Applications indexes

https://richonrails.com/articles/endless-scrolling

**Comment by TheDudeWithTheThing** [comment]
wooo!  Nice to get something out that these users can actually see

**Comment by markottaviani** [comment]
Truth!  Check out https://ophrescue.org/dogs though, any thoughts on how to clean up the grid?  Would like to keep it as a 3 across media grid

**Comment by TheDudeWithTheThing** [comment]
oh no, I thought they were all the same size, maybe we can make the boundary box the same size regardless of image size.  I need some better dev data.

Let me see what I can do.
