### ISSUE TITLE
Store private attachments on adoption application

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#450]
From one of our Adoption Coordinators.   This would probably be similar to how to attach documents to dogs.  

> Can we add a document upload box to the applications that only we can see. It would be for us to upload documents not the applicant? Or is there a way to add a picture/image to the comment box?
> 
> Written permission from landlords. Proof of vetting (if applicant doesn't use a traditional vet). Right now we just note the findings.

**Comment by TheDudeWithTheThing** [comment]
so these would be documents attached to `adoption_app` and not the actual adopter?  Can only be seen by admins and not adopters?

**Comment by markottaviani** [comment]
Can be seen by those that can see the adoption app after its created.  So no special permissions needed for this over viewing any other adoption app that's already been created.
