### ISSUE TITLE
Infinite Scroll should remember location

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#475]
If a user scrolls a few pages down and clicks on a link and then hits the back button, the user should be returned to the same location on the scroll.

**Comment by TheDudeWithTheThing** [comment]
Any idea what browser this isn't working on?  Seems like firefox, chrome and safari on a mac all behave as expected

**Comment by markottaviani** [comment]
On Chrome it is isn't working correctly on the users page.

So If I'm on https://ophrescue.org/users

Scroll down a page or two

Then click on a Dog that someone is fostering, and then hit the browsers back button I wind up at the top of the page.

**Comment by markottaviani** [comment]
Also requested a supportdetails.com report from the person that reported the issue.

**Comment by markottaviani** [comment]
User is on Firefox 48 / Windows 10.

I'm seeing the same issues though.  It seems like the scroll bar is going to the right position, but the data for the lower "pages" of info isn't getting re-queried right?
