### ISSUE TITLE
Dog Manager Scroll is Messed Up

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#477]
![2016-08-03_2041](https://cloud.githubusercontent.com/assets/793671/17386686/fc89e77c-59ba-11e6-9dd6-88699033c998.png)

**Comment by TheDudeWithTheThing** [comment]
This on prod or my new version?

**Comment by TheDudeWithTheThing** [comment]
hmm never got a prod login btw

**Comment by TheDudeWithTheThing** [comment]
oh man you merged the new branch, I wasn't done yet!

**Comment by TheDudeWithTheThing** [comment]
Fix here

https://github.com/ophrescue/RescueRails/pull/478

**Comment by markottaviani** [comment]
Sorry about that, I added an extra column on waffle to help communicate when stuff is done:

https://waffle.io/ophrescue/rescuerails
