### ISSUE TITLE
Show what dogs are in Boarding

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#487]
Dogs in boarding are currently assigned to a dummy User Account for a given Boarding Facility.  Add some kind of a view to make it easier to see what dogs are assigned to one of these boarding facilities.

**Comment by TheDudeWithTheThing** [comment]
do we just need a generic "boarded" or you want the association to the actual facility?

**Comment by markottaviani** [comment]
We could add property to the dummy user accounts saying that it's a boarding location. 

Then add a tab to the dog manager to show "in boarding"  and just filter where the foster assigned has the boarding property set to themselves.

**Comment by markottaviani** [comment]
Adding link to Facebook discussion: 

https://www.facebook.com/groups/348416295253712/permalink/1326452290783436/ 


Provide an easier method for staff to quickly identify what dogs are in boarding at what locations.

**Comment by markottaviani** [comment]
no longer needed
