### ISSUE TITLE
Possible js issues with Edge Browser

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#494]
Report from Edge Browser User:

Unable to update the address of adopters. 
Unable to Edit my own Comments

Will direct user to Chrome for now,

**Comment by TheDudeWithTheThing** [comment]
oh god edge, looks like jquery input mask is the culprit

**Comment by TheDudeWithTheThing** [comment]
and jquery validate is breaking IE 11

**Comment by markottaviani** [comment]
have not heard any user complains or issues for quite a while.  Closing.
