### ISSUE TITLE
As adopter link dogs to your application you're interested in.

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#527]
When an Adopter fills out an application they should be able to pick the dogs they're interested in in and have those linked to their application. 

Would it be possible to have the application automatically link a dog when the name get entered into the Dog Selection Box? Obviously if it does not match, a link would not be made.

**Comment by TheDudeWithTheThing** [comment]
Are dog names unique? You just want to autocomplete?

**Comment by markottaviani** [comment]
Names aren't unique, they can repeat sometimes.  

Probably autocomplete, and possibly some kind of a filter, probably the same thing we use to show "available dogs"



Mark

**Comment by TheDudeWithTheThing** [comment]
Sorry the nomenclature is escaping me here.  Can we just copy what's at the bottom to the top?  Is that what's being asked here?

https://cl.ly/341l1F2b2q14

**Comment by TheDudeWithTheThing** [comment]
oh this isn't even the one you assigned me, still clarify though

**Comment by markottaviani** [comment]
Currently, when someone fills out an application, they type in a text box the name(s) of any dog(s) they are interested in adopting.

That's done here https://github.com/ophrescue/RescueRails/blob/master/app/views/adopters/steps/_dog.html.erb with this question:
> (Optional)  What dogs are you interested in?

Then, once the application is completed, an OPH Volunteer goes into the application and links the dog(s) to the adoption application using the "Associate Dog with Application" dropdown that you show in https://cl.ly/341l1F2b2q14 .  This is kind of annoying for adoption coordinators to do, when we could probably have the adoption application do it instead.  


The existing Associate Dog with Application dropdown sucks as noted in #551 so my suggestion would be once #551 is completed, look into implementing that same improved selection method on https://github.com/ophrescue/RescueRails/blob/master/app/views/adopters/steps/_dog.html.erb

**Comment by TheDudeWithTheThing** [comment]
Perfect, I think that means chosen gots ta go

**Comment by markottaviani** [comment]
For sure

**Comment by markottaviani** [comment]
I think there is still a little bit to do for this one.  We'll need to add some of the dog linking functionality to https://github.com/ophrescue/RescueRails/blob/master/app/views/adopters/steps/_dog.html.erb

**Comment by TheDudeWithTheThing** [comment]
ha, why did I close this?

**Comment by danisaurio** [comment]
Hi! The adopters can only apply for one pet at a time or they may select multiple pets? can I apply to adopt 2 dogs (or 1 dog and 1 cat) in just one application?

**Comment by markottaviani** [comment]
Selecting multiple pets is okay, sometimes they’re interested in a few

**Comment by danisaurio** [comment]
Ok! So, should I remove the option "dog_or_cat" from the application?

**Comment by markottaviani** [comment]
That field can stay.  

This shouldn't require any new DB fields, as you're effectively just linking the adopter to the dog or cat via the "adoptions" or "CatAdiotions" model

**Comment by danisaurio** [comment]
Yes, I have that... I just don't see the point on selecting dog_or_cat if
on the next option I may select either dogs, cats or both.

Am I missing something maybe? Does that field has another purpose besides
helping the adoption manager to do the linking manually?

**Comment by markottaviani** [comment]
The adoption coordinators find it helpful for staying organized.

**Comment by danisaurio** [comment]
Ok, thanks! :)

**Comment by danisaurio** [comment]
Which pets should be pickable by the user? just the ones with status "adoptable"?

**Comment by markottaviani** [comment]
Same ones that are visible in the public gallery:

https://github.com/ophrescue/RescueRails/blob/master/app/models/dog.rb#L164

**Comment by markottaviani** [comment]
cancelling
