### ISSUE TITLE
Method for flagging invalid mailing addresses

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#542]
> Can you please see if there's a way that you can add a check box, or some kind of notation, so that when we have incorrect addresses those won't pull if you do a query for us?  We email/call for new addresses, but don't always get them and, obviously, don't want to keep sending out mailings to them until we have a good address.

> Jen & Mindy

**Comment by danisaurio** [comment]
@markottaviani could you please give me some insight on how the mailing addresses are fetched for the team to send mails later? I assume this is talking about adopters, not applicants?

**Comment by markottaviani** [comment]
All that should be needed is a boolean added to the `adopters` table, and a checkbox somewhere near where the address itself is displayed on the adopter's `show` page.  

Address fetching as been a manual SQL query in the past, so as long as the boolean is there and obvious that will filter them out.

**Comment by markottaviani** [comment]
Resolved in https://github.com/ophrescue/RescueRails/pull/1602/  thanks!
