### ISSUE TITLE
Adoption Coordinators can add Tasks to adopter's applications

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#547]
> Is there a way when we are adding or editing a profile to add under PRIVATE ATTRIBUTES a place to check for "HOME CHECK REQUIRED" since we do these for Pitbulls and a few other breeds?

Source: Gina Facebook

> I think the home check one is important. BUT while we are doing it - would we be able to add in a Medical Addendum Needed and Behavior Addendum Needed check off like the home visit? I'm all for getting more bang for our buck.

Jen - Facebook  https://www.facebook.com/groups/348416295253712/permalink/1371995469562451/?comment_id=1373073669454631&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by markottaviani** [comment]
Probably related to #124

**Comment by markottaviani** [comment]
1) An adoption coordinator flags an application as needing a special thing (home check, Medical Addendum, Belly Rub, etc.) 

2) Someone else then checks off that item as having been completed 

3) A comment stating who created the task and who marked the task as completed 

Really this sounds like Tasks, I'm assuming there are a ton of tasks that every application needs, occasionally some one-off tasks that are needed for one application but not for others, etc. Probably a lot of discussion could go into figuring out how to implement this correctly.

**Comment by markottaviani** [comment]
@lnzd17 any interest in taking a shot at this?  I started a discussion thread at https://www.facebook.com/groups/348416295253712/permalink/1388547331240598/ to see if we can hash out how  this might work.

**Comment by lnzd17** [comment]
I can definitely give it a shot! I will read up on it now.

**Comment by lnzd17** [comment]
@markottaviani  I have a few operational questions about this process (thought I'd ask here first before FB):
* Is there an operational point person that has the 'final' say for the adoption workflow?
* Are there any regulatory guidelines that have to be met for each adoption?
* What staff permission levels/position types are a part of this process?
* Does one person complete the whole approval process or are there handoffs?
* Can an application move back and forth on the workflow 'path' or does it only progress?
* Is there a simple workflow diagram, list, or documentation on the current process?

**Comment by markottaviani** [comment]
All really good questions, feel free to post these on Facebook.

**Comment by lnzd17** [comment]
will do! :)

**Comment by lnzd17** [comment]
@markottaviani  Just an update - I'm waiting on more information on the adoption workflow.  Stephanie said she would get it to me by the end of the week. Let me know if I can help out anywhere else in the meantime :)

**Comment by lnzd17** [comment]
update:  Sent follow up email to operations team to confirm if workflow is finalized.  8/19

[Adoption flow diagram (1).docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596b8905c878e5001f53ac75/125516c66e82c728ace21e0d46c9909533968aa681a9b94fab4ab090204720612809e36321cca164fd52690e050a1de853524d41f8a8dd2ff3be3574d85b58bbd16d5d74c66f13fdeed74cad1da862da11d1e9e1d30695aa2f2ff58f874a3c14041d89fc5c31a29d49cc59f748f300.docx)

**Comment by markottaviani** [comment]
So for a phase one for this item would probably just be  "free form tasks"  

Phase two can be adding default initial tasks

**Comment by markottaviani** [comment]
canceled
