### ISSUE TITLE
Adopter Waiting list

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#548]
> Is it possible to create a waiting list in DMS on the dog side? When we have a dog that is very popular and there is a long waiting line, sometimes it gets hard to see who is next and who passed. Maybe create a fixed summary field (just like medical) that is called Waiting List? ACs can add the next approved adopter waiting in line with the date and the applicant's name. The ACs would still make comment notes, but this will offer a quick look at the lineup.

Source: Jamie Facebook, 

See also related emails Sub: **Possible change to DMS**

Biz Contacts:
* Jamie B
* Laurie

**Comment by markottaviani** [comment]
Discussions on this are leading toward some some of a custom grouping of applications.  

* Admin creates a Waitlist
* Adoption Coordinators can then add Adoption Applications to the Waitlist
* Adoption Coordinators can view all adoption applications attached to a given waitlist (default sorting by read to adopt date)

Likely need some UI Changes to the top of the Adopter Index.  

I'm tempted to steal the how github issues does their filtering.

**Comment by TheDudeWithTheThing** [comment]
is this related to #357  ?

**Comment by markottaviani** [comment]
Nope!

**Comment by markottaviani** [comment]
Pending Response from OPH, on if this is the functionality they're looking for:

* Allow admins the ability to create a "wait list", essentially an arbitrary grouping of adoption applicants.  
* A wait list itself should have a name and possibly a brief description
* Allow Adoption Coordinators to add or remove applicants from one or more wait lists
* Have the ability to view each waitlist to see what applicants are on each waitlist, and sorted by Ready to Adopt Date.
* Being on one or more waitlists should be different than an applicant's status because

**Comment by markottaviani** [comment]
Additional Items:
* Some method for tracking who is added/removed from a given list (audit)

**Comment by markottaviani** [comment]
Pending question:  How to handle the ranking and ordering of members on a given waitlist.  Is is based strictly on the time and date someone is added to the list, or should the order of the list be manually manipulated?

**Comment by markottaviani** [comment]
Had some discussions this week, and I think I have the info I need to start working on this.

**Comment by markottaviani** [comment]
After discussions with the OPH folks looking for this feature, here is the breakdown.


* A new Waitlist model with a Name and a Description. 
* Many Adoption Applicants can be added to Many Waitlists.  
* Many Dogs can be added to a Single Waitlist.  A Dog cannot be one two waitlists at the same time.
* A waitlist might have 0 dogs and 0 applicants on it.
* Dogs and Adopters, when added to a waitlist have an rank on the list.  
* When dogs or adopters are added to a waitlist they are automatically added to the bottom of the list.  

* Admin permissions are required to create/edit/delete a waitlist
* Adoption Coordinator Permissions are required to add/remove/reorder applicants on the list
* Edit Dog Permissions are required to add/remove/reorder dogs on the list. 

Some Rough Screen Mockups are available here:  https://app.moqups.com/admin@ophrescue.org/OsQHWtgyhH/view/page/ad22d235b

This is a fairly complicated one so let me know if you have any questions, I can also get a call scheduled with the users if we need clarification on anything.

**Comment by taratip** [comment]
@markottaviani Can you give me permission to view the screen mockup? It said I was not authorized to view this project.

**Comment by markottaviani** [comment]
@taratip just sent you an invite

**Comment by taratip** [comment]
Thank you. I can view now.

**Comment by taratip** [comment]
Hi @markottaviani I'm a bit confused. I understand adoption applications can be added to a Waitlist but get confused when a dog being added to a Waitlist as well. What the waitlist should be looked like?

**Comment by markottaviani** [comment]
We have situations sometimes where there are a lot of people interested in a specific dog, or maybe a specific litter of dogs.  Adding a dog a waitlist helps keep track of what the people are waiting for 😄

**Comment by taratip** [comment]
I see. So, if the dog was reordered, wouldn't the application be moved too? I'm thinking of a row of adopter and dog... can we implement it something like this, http://sortable-bootstrap-table-rails.herokuapp.com/ ? This is the overview http://benw.me/posts/sortable-bootstrap-tables/

**Comment by markottaviani** [comment]
Nope, while the dogs and the applicants part of the same waitlist object they aren't blended together in order.    Applicants will be in order on the waitlist, dogs will just be "linked" to a given waitlist.  

There are four pages of screen mockups at the mockup link.

**Comment by markottaviani** [comment]
Cancelling feature
