### ISSUE TITLE
Add County to Address

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#549]
> Adding County would be helpful as it will save our reference checkers from having to look up the county on each application  for pitbull restrictions and home verification. Thanks! 

Source: Laurie via Email.

Might be able to find an external service for looking up county information based on the entered address.

**Comment by TheDudeWithTheThing** [comment]
think we'd hit 2500 requests a day?

https://developers.google.com/maps/documentation/javascript/geocoding

**Comment by markottaviani** [comment]
I think if we only hit the Google API when an adopter creates their
application, and store the result.   We should be totally fine wth a lot of
room to spare.  Most applications submitted in a day over the past year was
30.

I guess we should also hit the API when an OPH Staff member edits someones
address.  Plenty of API room to spare!

**Comment by MatthewDrouin** [comment]
If you run into issues where you actually hit it more than 2,500 a day you could just use USPS Address Verification 
https://www.usps.com/business/web-tools-apis/welcome.htm <https://www.usps.com/business/web-tools-apis/welcome.htm> https://github.com/gaffneyc/usps <https://github.com/gaffneyc/usps>

**Comment by TheDudeWithTheThing** [comment]
@MatthewDrouin out of nowhere!

**Comment by TheDudeWithTheThing** [comment]
do we have a google account to use for API keys and such?

**Comment by markottaviani** [comment]
Yes, Env Var GOOGLE_MAPS_GEOCODE will get you the API key.

And we already have http://www.rubygeocoder.com/ gem installed.
