### ISSUE TITLE
Determine RescueRails software License

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#550]
Need to attach an appropriate open source license to this project.

**Comment by markottaviani** [comment]
Possible Options:

Eclipse Public License
https://tldrlegal.com/license/eclipse-public-license-1.0-(epl-1.0)#summary

Apache License
https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

Mozilla Public License 2.0
https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)

Mozilla Public License 1.1
https://tldrlegal.com/license/mozilla-public-license-1.1-(mpl-1.1)

**Comment by TheDudeWithTheThing** [comment]
What exactly are we trying to prevent / say legally?

**Comment by markottaviani** [comment]
I think the concern is more around images and logos and stuff like that.

**Comment by markottaviani** [comment]
License will be set to Apache 2.0, working on applying headers and whatnot.
