### ISSUE TITLE
Linking Dogs shouldn't require clicking on the name from the dropdown

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#555]
If user types in the full name for a dog and click "Link Dog" without selecting it from the dropdown, user will receive a Not Found Error message.

If user types in part of full name of dog, and then click on the dog name from the dropdown the dog will be successfully added.

**Comment by markottaviani** [comment]
Not sure if duplicate dog names are a concern if we're filtering for only active dogs anyway.  

I was thinking it might be really cool to show a thumbnail preview of the dog in the autocomplete dropdown but that's for another time

**Comment by markottaviani** [comment]
Okay.. update on this. 

We do have dog name uniqueness validation

```
  validates :name, presence: true,
           length: { maximum: 75 },
           uniqueness: { case_sensitive: false }
```

So that should make this a lot easier to sort out

**Comment by TheDudeWithTheThing** [comment]
https://github.com/ophrescue/RescueRails/pull/559

done, will auto select on 1 result returned, is that how it used to work?
