### ISSUE TITLE
Searchable Staff Resources

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#573]
>Please add to your very long list of items for the website, a search option for Staff Resources.  We have volunteers and fosters looking for items and not sure where they are.  Plus, we've moved things around and they are in new places!  Thank you!!!

Source: Mindy Email

**Comment by TheDudeWithTheThing** [comment]
Looks like this is winning out in the poll about issues to work on. Is there any more info here?

What is a staff resource?
What is an item?
Moved real world objects or moved things on the web site?  If real world objects how are those being tracked today?

**Comment by markottaviani** [comment]
This is the /folders section of the site.  Basically it's a hacked together file sharing system using paperclip gem.  Could easily benefit from a lot of love and improvement in the UI space.

**Comment by lnzd17** [comment]
@markottaviani sorry for the delayed response. After ticket 608 I can take a crack at this one. Also still waiting to hear back on the adoption workflow ticket.

**Comment by markottaviani** [comment]
Awesome thanks!

**Comment by lnzd17** [comment]
@markottaviani  I am attempting to test out to current folder system on my local machine. I am about create a folder but not upload a file. I get the following message:

`missing region; use :region option or export region name to ENV['AWS_REGION']`

Does my environment need a secret variable?

**Comment by markottaviani** [comment]
Sent you some ENV vars you can use.

**Comment by lnzd17** [comment]
Update - working on adding a  search by filename on the folders#index
