### ISSUE TITLE
Restrictions to Behavior Status

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#574]
> Is there a way that we can make it so only certain people can change behavior status on a dog? 
> Perhaps change status to completed permission? Or training team permission?

> Source: Laurie L - Email

**Comment by danisaurio** [comment]
who should be able to change the status?
in order to extend the statuses from a boolean to include "completed permission"... would you prefer to add a "behavioral_status" attribute or change the "has_behavior_problem" datatype?

**Comment by markottaviani** [comment]
Hold off on this one for now
