### ISSUE TITLE
Security - Login Enhancements

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#580]
Security functionality need some love

Consider switching to Devise or another gem to standardize and improve instead of using the existing setup. 

Try to deal with
* Brute Force Passwords
* Enable CAPTCHA when multiple logon attempts
* Track IP and Logins
* Email Notifications on Logon
* Address MutliFactor

**Comment by markottaviani** [comment]
@TheDudeWithTheThing if you'd like to try and tackle something a little more interesting, this might be up your ticket.

**Comment by tobymurray** [comment]
@markottaviani - are there any ways an unauthenticated user (anonymous) is different from a user who has signed up but not set their password/signed in? I guess someone who has signed up has the opportunity to go through the "forgot password" workflow - anything else you can think of?

Is there any user registration (volunteer or staff) that is not driven by an administrator? E.g. a "sign up" button somewhere?

**Comment by markottaviani** [comment]
I think that’s all covered.  Only an admin can add a new user.

**Comment by tobymurray** [comment]
What does it mean for an account to be locked or unlocked? I see that they're unsubscribed from mailings, and it looks like they can't log in, but I'm not seeing why they would be locked/unlocked. What kind of things would cause an account to be locked, and what kind of things would cause an account to be unlocked?

**Comment by markottaviani** [comment]
Locked is situation where someone totally leaves the rescue.  Maybe they’re
“fired” or totally quit.  We don’t delete the accounts, as it makes it
easier to be aware if someone tries to revolunteer 5 year’s later or if
someone has comments on the system their name is retained.

So we do wind up with mutually exclusive types of user accounts:


ADMINS - Can add new users and modify anyone’s permissions

ACTIVE - Active Staff/volunteers that are contributing to the rescue.  Gain
access to lots of private information and ability to be granted additional
roles and responsibilities.


INACTIVE - people that said they wanted to volunteer in some way , but
either don’t do anything or haven’t done much of anything in a while.
Their access should be no different that a public anonymous user on the
website other than they have a Profile they can edit, and they should get
subscribed to the mailing list.  The hope is that they might step up in the
future and be more active.  so we might email them if there is an event in
their area and we need volunteers, etc.


LOCKED - They have either totally quit/vanishes or been terminated from any
involvement with the rescue.  We don’t delete user accounts, this provides
a record of anyone that left and why.  Also keeps names tied to
commits/audit trails in the system.


These are all Boolean in the system, and the ACTIVE/INACTIVE stuff is what
we’re working on in the other PR.

**Comment by markottaviani** [comment]
@TheDudeWithTheThing I know you've got us switched over to clearance gem already, can you give it a once over and see  what might be worth adding?  

Specific stuff:

1. Weak Password Checking (if this isn't already baked in)

2. Brute force Password Check/Throttle.
