### ISSUE TITLE
AWS RDS Class Change

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#588]
Switch from existing db.m3.medium RDS instance down to 

db.t2.medium  and purchase reserved instance

**Comment by TheDudeWithTheThing** [comment]
db.t2.medium == db.t2.medium ?

**Comment by TheDudeWithTheThing** [comment]
also I need to get back on this horse, what are the HOT ISSUES?   🔥   🚒

**Comment by markottaviani** [comment]
Whoops, db.m3.medium!

Any of the *Ready* stuff is good to go, nothing huge there but fairly straightforward https://github.com/ophrescue/RescueRails/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Aready

**Comment by markottaviani** [comment]
Conversion completed this morning
