### ISSUE TITLE
Two Levels of Volunteers

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#590]
> The goal is to have two levels of volunteers and to not delete any, unless they are locked for business purposes.  

> We have many that sign up and don't do anything or much, but I would rather keep them on as supporters and hope they step up one day, or donate or pass on good words about us.  These would be Volunteer Supporters and not have access to DMS staff resources, just their profile.

> I would have a second group called Volunteer Administrators or something that are the active volunteers, that have positions, jobs, need DMS access.  If someone gets active from the supporter group I would move them to Administrative group.

> So, I would add all new people to just Volunteer Support, and once I see them being active move them up, and if they are not active move them back.

Feature Biz Contacts:
* Jen 
* Laurie
* Joanne

**Comment by markottaviani** [comment]
Pending Clarification on the following:

If someone is considered "Volunteer Support" they can:
* login to DMS
* Access, edit and update their profile
* Do anything an anonymous public user can do
* Be automatically added to the volunteer mailing list


Should they be able to:
* View profiles of other users?
* View private dog data, or only see the standard public dog information?
* be granted any other roles or permissions (Adoption Coordinator, Reference Checker, Foster, etc.) or does their account need to be "Upgraded" First?

**Comment by markottaviani** [comment]
@blai00  Going to review this with the biz folks tomorrow, hopefully you can get started soon.  LMK if you have any questions.  Thanks!

**Comment by blai00** [comment]
hey mark, just read the requirements for this new change. just wondering when we see them "active" do they automatically become volunteer administrator or is it that someone who is already a volunteer administrator will move them up once they express their interest in helping out more to someone.

**Comment by markottaviani** [comment]
Someone with admin rights would need to apply the permission/setting to the
Volunteer’s account.
