### ISSUE TITLE
Adoption Coordinators should be able to edit Applicants References

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#595]
Source:  https://www.facebook.com/groups/348416295253712/permalink/1329164933845505/

As an Adoption Coordinator I should have the ability to update an Applicant's references, as these frequently change.   The changes should be automatically logged in the comments section.

**Comment by blai00** [comment]
should there be a new permission for adoption coordinators that could edit it?
should this also be available for admins or just specifically for adoption coordinators

**Comment by markottaviani** [comment]
No new special permissions.  Same folks that can edit an adoption applicant's address should be able to update the references.  Ideally try to follow that same behavior.
