### ISSUE TITLE
Dog Gallery Cache Issues

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#601]
Staff Identified a dog in 'adoptable' status but isn't showing up in the Gallery.  

I was able to confirm, but not sure of the cause yet.  Investigating....

**Comment by markottaviani** [comment]
So, this was some kind of a caching issue.  Making a quick update to the dog's profile (which caused the dog's ```updated_at``` triggered the refresh and got the dog back in.  Dog's last update was 2 days ago.  

@TheDudeWithTheThing 

I took an amateur cut at doing fragment caching on the dog gallery in b0ada5817497ffed8875901da365e8d5af3f2c69   

Any thoughts on what I might be doing wrong here?

**Comment by markottaviani** [comment]
Rolled back Gallery caching until this is fixed.

**Comment by TheDudeWithTheThing** [comment]
I'm almost positive we tried to do this already and had the same result, I'll take a quick look now and then on the train in tomorrow.

**Comment by TheDudeWithTheThing** [comment]
I wonder what it'd be creating for a cache key with the array `@dogs`, we probably want to move this into the `dog_row` template, let me PR quick

**Comment by TheDudeWithTheThing** [comment]
what are we actually trying to do here?  just speed up search?  This didn't help much

https://github.com/ophrescue/RescueRails/pull/602

**Comment by markottaviani** [comment]
Trying to speed up the dog gallery. 

Even with the eager loading I put in, because of how we do the dog photo query to figure out what the cover photo is for the dog (by a sort), we still wind up doing 30+ database calls each time a page of the dog gallery is viewed.

Our database is on AWS Virginia and the webserver is with Linode in Newark, NJ.    So I try to be wary of pages with lots of database calls due to the latency.

**Comment by TheDudeWithTheThing** [comment]
ok let me take a stab at sniping those N+1s, should be pretty easy

**Comment by markottaviani** [comment]
closed by #602
