### ISSUE TITLE
Add comment box pinned to top of dog profile for ACs (ie like Medical Summary)

### ISSUE THREAD

**Issue by collinsc67** [ophrescue/RescueRails#607]
I think it would be useful to ACs to have a comment box stationary under the Medical Box where foster families could put comments specific to fielding adoption applications, i.e., dog must have 6' fence or home with no children, experienced dog owners only etc. It seems many times these kinds of comments end up being buried among other comments and can easily be overlooked by ACs. It's for the fosters to enter info for ACs to read to ID ideal adopters. Maybe the title could be Ideal Home Description or something.

**Comment by markottaviani** [comment]
Thanks for your suggestion. #614 - Behavior Issues should be used for this type of information.
