### ISSUE TITLE
Changes to who or how adoption applications are assigned?

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#615]
This is just a marker for a future discussion with OPH.  Right now the users aren't sure what they want :)

**Comment by blai00** [comment]
Could I get some clarification of what is expected in this change?

**Comment by markottaviani** [comment]
This was something mentioned in passing, but we don't have any details yet.   Make sure to use the Kanban board at https://waffle.io/ophrescue/rescuerails/ for current item ranking.

**Comment by markottaviani** [comment]
Also, @blai00 at the moment I'm not sure of what I'd recommend you take on next, most of the other item are pretty significant.
