### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by tobymurray** [ophrescue/RescueRails#619]
I made my way here through contacting ophrescue.org but I don't see a "development volunteer" option on the form on that site. Is this repository open to contributions? Perhaps worth a paragraph in the `readme` about how to get involved if so?

As written it's not clear what tickets are "next up" etc, and as they're generally relatively sparsely populated it seems difficult to just pick one up.

**Comment by markottaviani** [comment]
Thanks @tobymurray  I've updated the volunteer application as well as our Readme file
