### ISSUE TITLE
Add a new permission for Medical and Behavior Boxes

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#630]
> Is there a way to have the medical and behavior box access under a separate check box other than the Add Dogs one?  We have certain ACs who are responsible for our behavior dogs and fosters too (medical as well) that will need to add notes into those boxes.  However, they don't need access to add dogs.

Story:
As an Administrator I need to be able to grant a specific permission to Users so they can be permitted the ability to edit the Medical Summary and Behavior Summary Fields for Dogs. 

As a user with Medical and Behavior Summary Update permissions, i need to be able to update the Medical Summary and Behavior Summary Fields for Dogs.

Acceptance Criteria:
- [x] Administrator can add and remove the Medical/Behavior Summary Permission from other users
- [x] A user without the Medical/Behavior Summary Permission is unable to edit the Medical or Behavior Summary fields for Dogs
- [x] A user with the Medical/Behavior Summary Permission can edit the Medical or Behavior Summary fields for Dogs.
- [x] A user with the Add Dogs permission is no longer able to edit the Medical or Behavior Summary
- [x] Permission should have a clear description visible to both a User or an Admin.
- [ ] rspec tests that verify the above criteria

**Comment by blai00** [comment]
Is this on the admin side of things?

**Comment by markottaviani** [comment]
Yup, did you want to take a shot at it? 

I can add some more details.

**Comment by blai00** [comment]
Yes I would like to take a shot at this.

**Comment by markottaviani** [comment]
Doc updated

**Comment by blai00** [comment]
how are we currently defining if the person is an admin? is this a boolean check? or are the pages that are used for editing and deleting only accessible by admin already?

**Comment by blai00** [comment]
also is there a way to create a test user? or do i have to go into the rails console and manually create it through that.

**Comment by markottaviani** [comment]
See ```db/seeds.rb``` for default admin login info.  You can then use that admin account to create test users and mess with their permissions, etc. 

is_admin? is defined in app/helpers/sessions_helper.rb
