### ISSUE TITLE
Dogs Index Render Bug

### ISSUE THREAD

**Issue by blai00** [ophrescue/RescueRails#671]
Steps to Reproduce
- Log in as admin
- Go to /dogs (dogs index)
- Select Manager View ("Dogs Manager" should be the title of the page)
- Log out 
- Go to /dogs (dogs index)

At this point, you should still see the title "Dogs Manager" rather than "Our Dogs"

**Comment by markottaviani** [comment]
Bug Confirmed. 

Desired behavior after going through the steps that @blai00 mentions above is that the header should say "Our Dogs" when looking at the Gallery, however it shows "Dogs Manager" when looking at the gallery even when logged out.

**Comment by blai00** [comment]
Since I found the bug, I will investigate for the time being of what solution can work for it.
