### ISSUE TITLE
Review Google Adwords Account

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#708]
We have a Google Adwords Grant account, but we don't give it much attention or tuning, so it could probably use some improvements.  

Primary conversion goal we're tracking is adoption applications.

**Comment by iantalarico** [comment]
@markottaviani I poked around a little last night and this morning.  

Who was running this before? I think it would be nice to get a status on what was done and why.  

Some of the ads seem to be around donations and some around adoption are specific goals around either?

Some of the ad text looks like it could use some love.  Is there a media person for this?
