### ISSUE TITLE
Require Date of Birth for Applicants Under 21

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#710]
If an applicant answers "No" to the "Are you at least 21 years old?" question on the adoption application, require them to enter their date of birth.  

Date of Birth & Age should be displayed on the adoption application view page.  

Requested by Laurie

**Comment by iantalarico** [comment]
@markottaviani This looks like a good one for me to start on, what do you think Mark?

**Comment by markottaviani** [comment]
Go for it, thanks!

**Comment by nickcianci** [comment]
I can work on this one if you guys aren't already planning to work on it.

**Comment by markottaviani** [comment]
Go right ahead, thanks!

**Comment by Autumn-Martin** [comment]
Taking this over on a fresh branch, since there's been a ton of changes since May last year.

**Comment by nickcianci** [comment]
I have an open pr for this one - https://github.com/ophrescue/RescueRails/pull/1185
It was ready for merge on 5/8/2019

**Comment by markottaviani** [comment]
Sorry for all the confusion to both of you.  I’ll review the existing PR
this evening and get back to you. Thanks

**Comment by markottaviani** [comment]
Okay again, very sorry that the PR fell off the radar. I'll get this merged and wrapped up this week.

**Comment by nickcianci** [comment]
No problem. Just thought you guys stopped working on the app for a while. Didn't want someone else to duplicate effort though

**Comment by markottaviani** [comment]
Merged via PR #1401
