### ISSUE TITLE
Improve Dog Manager Index View

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#731]
Improve the Dog Manager Index view.

Possibilities
* Add Dog Thumbnail
*  Improve Mobile Friendliness
*  Make it easer to see if a dog has an Adoption Coordinator ( #732 )

**Comment by lazylester** [comment]
I suggest this should be done after the page is upgraded for BS4.1 rather than before.
I'll tackle the upgrade for this page as my next BS4.1 upgrade.

**Comment by TheDudeWithTheThing** [comment]
agreed

**Comment by markottaviani** [comment]
Done for now, any future Dog Manager view tweaks will be handled as separate items.
