### ISSUE TITLE
Make it easer to see if a Dog has an Adoption Coordinator

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#732]
> I think I requested consideration for some sort of special identification if a dog has an assigned AC.  Whether the dogs name is a special color or highlighted, etc.  Of course I would suggest this be shown in the dog manager view and then when the dog is linked in the app.
> 
> I have noticed we are running into ACs who don’t realize the dog has an AC and tells the adopter they are AP.

Per Jamie B

**Comment by TheDudeWithTheThing** [comment]
what info is needed here?

**Comment by markottaviani** [comment]
Info needed was more of a usability discussion.  I'm not sure if a color change is going to be right way to communicate that a dog has an adoption coordination.   Feels kind of non-obvious to me.

**Comment by TheDudeWithTheThing** [comment]
was thinking a column with a check mark, I thought I saw somewhere "make it a color"

**Comment by markottaviani** [comment]
Resolved as part of the Dog Manager upgrade to Bootstrap 4.1
