### ISSUE TITLE
Upgrade to Bootstrap 4.1

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#755]
Bootstrap 4.1 has arrived, and we're still on Bootstrap 2.3.2

We should transition the site to Bootstrap 4.1, keeping existing layout and functionality.  

The upgrade to Rails 5.1 added in webpack and yarn support too so we can get bootstrap out of our /vendor directory

Whomever takes point on this can also use our Browserstack account to help with testing.

**Comment by lazylester** [comment]
What is the wepack/yarn strategy you're suggesting for BS4.1?

AFAIK, you'd have to put the BS javascript in an npm_modules directory. What about the CSS, though, doesn't it still have to be in vendor/assets (or lib/assets or app/assets)?

Webpack seems to make sense for single-page apps, with a ton of js written in ES6, but we just have a few snippets, and a few external libraries (jQuery, BS etc).

**Comment by markottaviani** [comment]
You can disregard that.  There is an official bootstrap gem now so that
would probably be the best way to pull it in.

**Comment by markottaviani** [comment]
Tunnel

**Comment by markottaviani** [comment]
Closing this one out since BS4.1 is now integrated and available.
