### ISSUE TITLE
Photo Gallery System

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#757]
Photo Galleries!

Users with an Edit Gallery Permission should be able to modify and create photo galleries.

* Create a gallery
* Create a sub-gallery
* Upload Photos w/ Descriptions 
* Galleries should be pinable or set to a fixed order

**Comment by lazylester** [comment]
is it possible to get from the OPH requester the url of an example website that has the features they would like to see?

**Comment by markottaviani** [comment]
cancelled.
