### ISSUE TITLE
Fix 404 Errors for glyphicons

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#760]
Pages are trying to access `/assets/glyphicons-halflings.png` and getting a 404 error. 

Probably fix: https://stackoverflow.com/questions/21103603/glyphicons-not-properly-precompiling-in-production-rails

**Comment by markottaviani** [comment]
nginx config fixed, site will now correctly redirect.

**Comment by markottaviani** [comment]
closed by mistake!

**Comment by Autumn-Martin** [comment]
Closing this -- it's been resolved.
