### ISSUE TITLE
Microchip data cleanup and validation

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#762]
Microchip data is a mess, and isn't entered consistently.  

This can cause problems when someone tries to search for a microchip and can't find the right dog.

build out better validation rules for data entry and clean up existing dirty data

**Comment by danisaurio** [comment]
do you have the microchip expected format (or formats)?

**Comment by markottaviani** [comment]
Known Valid formats are:

10 Digit Alphanumeric     (ex: 4C3413135C or 0A1213874E )
15 digit Numeric, always starting with a nine . (ex:  900164000395589 ) 

Possibility of future / additional formats exists.

**Comment by markottaviani** [comment]
Format validation rolled out, and old data cleaned up
