### ISSUE TITLE
List of supported browsers/platforms

### ISSUE THREAD

**Issue by lazylester** [ophrescue/RescueRails#766]
Probably the README is the best place for this, so that devs are all "on the same page". What browsers (including mobile and tablet) are we supporting?

**Comment by markottaviani** [comment]
My intention would be mirror the Bootstrap 4.x support.  https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/

**Comment by lazylester** [comment]
OK, thanks @markottaviani I'll include a note to this effect in the README as part of the Bootstrap 4.1 upgrade.

**Comment by lazylester** [comment]
@markottaviani the question is broader than just what is supported by Bootstrap 4.1. The specific platform viewport sizes that we're designing for should be specified.

Of course, it's easy to make the requirement very broad, but, as I'm currently discovering, (probably others knew this), designing for a wide variety of platforms can be a lot of work, even though they're supported by Bootstrap... that's a _necessary_ but not _sufficient_ condition.

Bootstrap compatibility relates more to browsers than devices, and they often have polyfills for older browsers.

For example, I'm currently tuning the manager view for the iPhone6, but I don't know if this is required, desirable, or a waste of time.

**Comment by markottaviani** [comment]
You're right, supporting a large number of devices and view sizes can be a ton of work.  Unfortunately Google Analytics doesn't provide good data.  (A lot just report as "Apple iPhone") 

For the Dog Manager let's target these mobile devices as a baseline:
- Samsung SM-G930V Galaxy S7
- iPhone 8
- iPad 9.7 Inch (current)

Start with that and see where the complaints are.
