### ISSUE TITLE
Searching for a Dog when logged out throws a 500 error

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#771]
Running a dog search when not logged in throws a 500 error

`/dogs?utf8=%E2%9C%93&search=Whatever&commit=Search`

```
undefined method `paginate' for nil:NilClass
app/controllers/dogs_controller.rb:263:in `for_page'
```

**Comment by lazylester** [comment]
Presumably the search should fail, but more gracefully than 500. Flash error message seems appropriate, do you agree? What would be the response elsewhere to unpermitted action?

**Comment by lazylester** [comment]
@markottaviani How exactly are you doing a search without being signed in?

**Comment by markottaviani** [comment]
I’m just going directly to the full URL with the search values in the
address.

My assumption is this is folks who’s sessions have expired or they
bookmarked a search result.

If they aren’t logged in, they should get bounced to the login page and
then bounced back.

**Comment by lazylester** [comment]
Where is the mechanism for session expiry? I haven't found it.

Seems as if they would have to log out and then return to the bookmarked page, as you mention.

**Comment by TheDudeWithTheThing** [comment]
`if current_user.nil?`

weird though, this should be handled way before hitting the Dog#index action, was this a problem before the changes went out?

**Comment by markottaviani** [comment]
Seems like this didn’t start cropping up until after the release.
