### ISSUE TITLE
Swap Paperclip gem to ActiveStorage

### ISSUE THREAD

**Issue by TheDudeWithTheThing** [ophrescue/RescueRails#776]
Paperclip goes away soon in favor of Rails 5.2 ActiveStorage.

https://robots.thoughtbot.com/closing-the-trombone

**Comment by lazylester** [comment]
well... just for clarity... Paperclip is not going away, and if we choose to, we can continue to use it, probably for many years, until it becomes incompatible with some future version of Rails or Ruby.

The anticipation of that possible future incompatibility, or its eventual arrival, seem to be the most compelling reasons to remove it from this project. Unless someone can offer another motivation.
