### ISSUE TITLE
broken link in pdf document

### ISSUE THREAD

**Issue by lazylester** [ophrescue/RescueRails#792]
the document: https://ophrescue.org/docs/blue-adult-packet-1.16.17.pdf has a broken link to the petfinder site.

The link  http://www.petfinder.com/pet-health/developmental-stages-dogs-life.html no longer works and the document referenced does not appear to be anwhere else on the petfinder site.

(Also, while you're editing this document, page numbers would be useful!)

**Comment by markottaviani** [comment]
Found a word doc version of that PDF so I should be able to sort that out

**Comment by markottaviani** [comment]
Issue was resolved in updated adoption packet: https://ophrescue.org/docs/Adult-Adoption-Packet.pdf
