### ISSUE TITLE
Image not found: /assets/no_photo.svg

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#812]
Path to `/assets/no_photo.svg` isn't valid with asset pipeline.  

https://cl.ly/2m3V1Z1G2A2h

**Comment by lazylester** [comment]
@markottaviani  is app/assets/images/no_photo.svg actually present on the staging server? I imagine it must be there as it's in the repo. But I have to ask b/c the image works in development env.

**Comment by lazylester** [comment]
in dev:
http://localhost:3000/assets/no_photo.svg #=> 200 OK

however:
https://beagle.ophrescue.org/assets/no_photo.svg #=> 404 not found

**Comment by lazylester** [comment]
OK I understand it now... you can't pull the asset directly with the url, it has to go through the asset pipeline manifest... I'll look into it

**Comment by markottaviani** [comment]
Verified, thanks!
