### ISSUE TITLE
Dog Index mobile view dog name text overlaps

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#828]
![unnamed](https://user-images.githubusercontent.com/793671/42603532-37001fbc-853c-11e8-90f0-62334fbbc2a0.jpg)

**Comment by lazylester** [comment]
Is there a reason why users may set the tracking id (in edit, but not when adding a dog)?

I would have imagined that the automatically assigned tracking id should meet all the use cases. 

In permitting users to set the tracking id, not only do we need to accommodate edge cases (as above, where tracking id has been set to 1000000), but we need to validate uniqueness and format (numeric). When a user is trying to set a unique tracking id, they just have to keep trying to find one that is unused.

**Comment by markottaviani** [comment]
Nevermind, don’t worry about the edge case. No action needed. I’ll get rid of the junky tracking id

**Comment by lazylester** [comment]
I think there could be overlap for long dog names (also unusual).

But my question relates less to the overlap (therefore off-topic I admit) than to the need for editing tracking id at all. Is there a use case for editing tracking id? The uniqueness requirement makes user config of this field a "hit and miss" proposition.

**Comment by markottaviani** [comment]
Yeah, for reasons I've never quite understood they want the ability to update and set these tracking ids.  I thing there remains an effort to attach logic to the meaning of the tracking IDs.  (All the pups in the same litter are in a sequence, etc.) .    In short, it needs to keep working the way it does.  There is an extremely limited group of people that actually add dogs to the system, so whatever logic they're using seems to be working.  So, the tracking ID functionality should stay as-is.  

The long dog names is going to be a thing for sure.  In production right now you can see things like dogs with the name of `David Wise (US Olympic Medal Winners Litter)` . https://ophrescue.org/dogs/7432

If needed I think trimming the full dog name is fine  `David Wise (US...` for mobile, certainly better than having the text overlap.

**Comment by lazylester** [comment]
The ability to edit tracking id causes a big problem. Here is the scenario...

Suppose the last automatically assigned tracking id is 1000.
Suppose a user adds a dog, and then edits the tracking id to 1010.
When several more dogs are added, and the last automatically-assigned tracking id is 1009, then adding the next dog will fail (I've confirmed this) with no ability to recover, and it will not be possible to assign any further dogs until the tracking id for the dog with tracking id 1010 is edited and its tracking id changed.

**Comment by markottaviani** [comment]
The tracking_id stuff predates the webapp by a year or two, and goes back to the spreadsheets they used to manage.  I'll bring this back up with them again the next time I talk to them, and the litter name stuff as well.  However, any major enhancements there should really be part of a different pull request and I don't except clarity on how to proceed from the rescue immediately.

**Comment by markottaviani** [comment]
I have some time available, so I'll make some adjustments to the mobile view.  Regardless of liter groupings or anything else, well still have situations where the dog name is just long.

**Comment by markottaviani** [comment]
Fixed in d940a236922ec6f7ae9667103372bd704eccfb41
