### ISSUE TITLE
Potential for user-edited tracking_ids to cause validation failures for new created dog records

### ISSUE THREAD

**Issue by lazylester** [ophrescue/RescueRails#831]
see the scenario described here: https://github.com/ophrescue/RescueRails/issues/828#issuecomment-405102049

Opened as a new issue as it will not be resolved with issue #828

**Comment by lazylester** [comment]
noting here, for posterity, that the addition of a new `litter_name` attribute can be considered as a way to group pups by litter, instead of assigning sequential tracking_ids. This will also obviate the long strings that are sometimes appended to dog names to convey litter associations.

**Comment by markottaviani** [comment]
cancelling this issue, manual tracking ID have been generally used to backfill data.  Will reopen in the event there is an impact.
