### ISSUE TITLE
Dog Documents should be visible on Dog Show Page

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#837]
Dog documents are only visible from the Dog Edit screen, they should be downloadable/visible from the Dog Manager Show screen

**Comment by lazylester** [comment]
I noticed this... wasn't it always this way? I recall wondering why.

**Comment by TheDudeWithTheThing** [comment]
someone trying to sneak in features as bugs??

**Comment by lazylester** [comment]
possibly, @TheDudeWithTheThing , I could be mistaken, but I remember thinking it was strange behaviour. Anyway, we should fix it and make it work according to the "principle of least surprise"

**Comment by markottaviani** [comment]
haha, it was listed as "Attachments".

https://github.com/ophrescue/RescueRails/blame/37502585eee6163e50965bf6c62a831032e858d4/app/views/dogs/show.html.erb#L220
