### ISSUE TITLE
Dog Name search not refreshing possibly wrong search results?

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#845]
> Ran a query for dog name "Gold."  This yielded no change to the list of dog names.  Tried filtering by name and it did not yield the correct results.
> 
> Performed around 8:45-8:55am today (7/16/2018) in FF v61.0.1
> 
> Query: https://ophrescue.org/dogs_manager?filter_params%5Bsearch%5D=gold&filter_params%5Bsort%5D=name
> Note: Tried using a capital G as well
> 
-Steph Acker

> When I am searching by names. I typed in Wile E McScruffy, Wild Thing, and Serenity and it pulled up their DMS profiles. I hit the name search and typed in Bahama Momma, Tone Loc, and Malibu and nothing happened on the page. Usually a little blue bar will go across the top of my screen when the internet is switching pages, but it didn't for these three. It just stayed on the main page where it lists all the dogs in the rescue. 
- Elizabeth Grimsley

**Comment by markottaviani** [comment]
I was able to replicate error in prod.  Not yet able to replicate problem in in test environment.

**Comment by lazylester** [comment]
it may be browser-related. It's working on chrome but not ff

**Comment by lazylester** [comment]
confirming ff fails in dev env... I'll dig in

**Comment by markottaviani** [comment]
This appears to have been fixed by by PR #850 I'm getting good search results back.  The checkbox to search by name wasn't getting picked up correctly.
