### ISSUE TITLE
Adjust location of Dog Status on Profile

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#846]
> I was looking for it along the side where it used to be.   Seems like it will be missed a lot on the top when the names are long.
-Mindy

https://cl.ly/360G383f2t1j

**Comment by markottaviani** [comment]
I think just even moving the stuff boxed in red in the screenshot above onto a new line under the Dog's Name would be sufficient for now.

**Comment by lazylester** [comment]
yes, the red-boxed stuff prob should be moved to its own line.

but the issue reported here is not being able to find the foster location. It's further down the list. I'll move it up.

**Comment by markottaviani** [comment]
Thanks, I'm reading the triaged items too fast
