### ISSUE TITLE
Improve test suite with browser testing for IE and FF

### ISSUE THREAD

**Issue by lazylester** [ophrescue/RescueRails#866]
The only way for new devs to contribute without regressions is to have a comprehensive test suite.

**Comment by lazylester** [comment]
suggestion from slack is to look at [https://gist.github.com/johnmeehan/b7795f08c037a13f5b694ee8209be65e](https://gist.github.com/johnmeehan/b7795f08c037a13f5b694ee8209be65e)

**Comment by markottaviani** [comment]
Firefox support added in PR  #867

**Comment by lazylester** [comment]
BrowserStack has taken an action item to put a reference implementation of browserstack+rspec+capybara in their [github repo](https://github.com/browserstack) as I have been unable to get IE testing working on their platform. Ref browserstack trouble ticket #112236.

**Comment by lazylester** [comment]
closed by PR #897
