### ISSUE TITLE
set needs_foster to false when dog is adopted

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#879]
if dog status is changed to adopted, completed or trial adoption, set needs_foster to false

also (note to self) run some SQL cleanup of old dog records that still have needs_foster = true

**Comment by lazylester** [comment]
It seems that "needs_foster" should not be a database attribute, but instead should be derived from status by:
```
def needs_foster
  !["adopted", "completed", "trial adoption"].include?(status)
end
```
This also produces the (apparently desirable) condition not articulated in the issue description, that needs_foster should become true if (for example) status changes from "adopted" to "returned".
