### ISSUE TITLE
Fail gracefully if audit user doesn't exist

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#946]
There is a chance that an old user account from years ago might not exist anymore.  If the audit display tab can't lookup a specific user under a given user_id, just display as something like "Unknown User(99)" where 99 is the user_id.

**Comment by danisaurio** [comment]
I'm trying to reproduce the issue. What's the workflow that would make a user receive this error?
Actually I'm handling it with a rescue over RecordNotFound when a user enters a URL with an invalid user id ("~/user/99" for example) is that what you need?

**Comment by markottaviani** [comment]
* login under your local admin account on the oph web interface 
* Create an adoption application
* Create a dog
* Create a new user account and grant them all permissions, (new-user)
* Login as new-user
* Edit a few fields on the adoption application, add a comment to the adoption application
* note that the comment is displayed and shows who the author was, and note that change records of new-user's edits to the adoption application also show up in the audit tab for the adoption application.
* Edit a few fields for the dog record using new-user
* note that the comment for the dog is displayed and shows who the author was, and not that the changes to the record of new-user's edits on the dog also show up in the audit tab for the dog 

Now, logout as new-user
go to the database and delete new-user from the users database table

login as your admin account
Try to view the manager view for the dog, and try to view the comments & audit data for the dog, page will throw an error b/c the referenced user record does not exist.

Try to view the adoption record, and try to view the comments and audit data for the adoption application.  Page with throw an error b/c the user does not exist.  


Fix, If user record cannot be found, Web UI should just display "Deleted User"

**Comment by danisaurio** [comment]
I was able to reproduce what you asked (thanks for the step-by-step explanation!) but it seems that the issue is already solved
comment on application:
![comment on application](https://user-images.githubusercontent.com/41554471/86066174-52dd9b80-ba26-11ea-908b-2527b4287783.png)
actions on dog register:
![actions on dog register](https://user-images.githubusercontent.com/41554471/86066198-638e1180-ba26-11ea-8680-268abb8f866c.png)
And for what I saw on here, it appears to be code from 3-6 years ago
am I missing something?

**Comment by markottaviani** [comment]
Thanks for confirming, sorry for the wild goose chase!
