### ISSUE TITLE
Switch to Bcrypt password strategy

### ISSUE THREAD

**Issue by lazylester** [ophrescue/RescueRails#947]
This can be done without requiring the user to reset their password:

1. add a second password field, `bcrypt_password`, to the User model
2. when a user first logs in, confirm their p/w using the current `encrypted_password` field, _and_ save their password bcrypt-encrypted in the new `bcrypt_password` field, and also set the `encrypted_password` field to nil
3. on subsequent logins, detect that the `encrypted_password` field is nil, so check against `bcrypt_password`

**Comment by TheDudeWithTheThing** [comment]
I thought about this too but wanted to avoid hacking the clearance gem. Not only that but then the hack would live on forever as we have no real time frame of when all the passwords are migrated over.  I'd rather go clean break, it's not 100% unheard of to be forced to reset your password.

**Comment by TheDudeWithTheThing** [comment]
> Hacking the clearance gem is as simple as overwriting a method in (e.g.) our /lib/clearance/xyz.rb file... no need to change the clearance code.

I agree, but then this code lives forever, unless we time box it. You have 2 months to change your password.

> but my email comes in on my computer, which is at home

I have to imagine 99% of the people doing this on their phone have their email hooked up to their phone, judging by the comments made on FB.

The trade offs here are, make it painful for our users for 5min or make it painful for us developers for the next few months.

**Comment by lazylester** [comment]
What is the pain that developers suffer for the next few months? Maybe I'm missing something. It all happens without developer involvement. Nothing to think about until some point maybe a year in the future when all active users have switched to bcrypt passwords.

It's not "painful for the user for 5min" if the user is at an adoption event, trying to log in on someone else's computer, and they don't have access to their email account.

It can be made seamless and invisible to the user, so why not do that?

**Comment by lazylester** [comment]
looks as if Thoughtbot has implemented a very [similar migration strategy](https://github.com/thoughtbot/clearance/issues/140) to the one I'm suggesting. It appears to be baked in to the Clearance code.

Instead of a new `bcrypt_password` column, they are able to detect whether the encrypted password string was produced by SHA1 or Bcrypt.

Thoughtbot, too, regards forcing users to reset passwords as undesirable when a seamless migration is possible.

**Comment by TheDudeWithTheThing** [comment]
The pain comes when clearance has a security vulnerability in it and we have to upgrade which breaks whatever hack we have there. The main reason to move to this gem is so we don't have to think about login anymore. Having code in there that hacks / fights the gem doesn't get us there.

> It's not "painful for the user for 5min" if the user is at an adoption event, trying to log in on someone else's computer, and they don't have access to their email account.

I can't accept this as a valid reason. There's no situation where someone doesn't have access to their email in 2018. You're reaching here @lazylester, reaching!

So I think with that similar migration strategy link we can add the Bcrypt stuff to the `WoofBark` strategy and it should be transparent. Also that link is from 7 years ago, we're slightly behind the times here.

What would you say is an acceptable amount of people that have logged in before we can go all bcrypt?  Or an acceptable amount of time?  Should we also mark a user as bcyrpt so we can have some sense of how many have logged in?  Or I guess we could throw in the last logged in tracking to clearance first before the swap as it's part of the requirements already.

You know, the other option is to keep the `WoofBark` password strategy forever, then this whole discussion is moot.

**Comment by lazylester** [comment]
Yes, the link is from 7 years ago. Clearance has had a migration strategy built in since then. I cited that link b/c it best describes the rationale and the technique. The fact that it was 7 years ago is not salient, the proposed method was subsequently incorporated into Clearance.

The questions you ask, "what is an acceptable amount of people" and "what is an acceptable amount of time" are all reasonable, easy to answer and don't pose obstacles.

I don't know what is meant by the WoofBark strategy. We should migrate to Bcrypt, and do it in the way that is invisible to the user, as the Clearance authors have accommodated. No pain necessary for devs or users.

**Comment by TheDudeWithTheThing** [comment]
ha, `WoofBark` is what I named our current way of encrypting passwords, which was moved to a clearance compatible class as part of the migration. 

https://github.com/ophrescue/RescueRails/blob/master/lib/password_strategies/woof_bark.rb

I can't imagine they change the interface here so hiding all the current to bcrypt logic here should be safe.

**Comment by lazylester** [comment]
"There are only two hard things in Computer Science: cache invalidation and naming things."

**Comment by TheDudeWithTheThing** [comment]
so true, so true

**Comment by TheDudeWithTheThing** [comment]
FYI I plan to go at this from the other way so the end result is us not mucking with the gem / putting more work up front now. The planned PRs

1. Create column on `users` called `woof_bark_password`. (make the name as dumb as possible so we're sure to delete it).
2. Modify `PasswordStrategies::WoofBark` to populate both `woof_bark_password` and `encrypted_password`.
3. Create rake task to copy value from `encrypted_password` to `woof_bark_password` where `woof_bark_password is null`
4. Modify `PasswordStrategies::WoofBark` to validate against `woof_bark_password` and update `encrypted_password` to have the bcrypt version of `woof_bark_password` on successful login.
5. Wait X amount of time.
6. Switch clearance to use `Clearance::PasswordStrategies::Bcrypt`.
7. Delete column `woof_bark_password` as well as class.
