### ISSUE TITLE
Event Page should support Google Rich Results

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#996]
https://developers.google.com/search/docs/data-types/event

**Comment by muhannadnouri** [comment]
I would like to work on that if that's okay. Let me know!

**Comment by markottaviani** [comment]
@muhannadnouri I think you may have had a comment on this one already?  This would be a great initial contribution if you're still interested.

**Comment by muhannadnouri** [comment]
I'll look into implementing this feature for an initial contribution!

**Comment by Jngai** [comment]
I can work on this.

**Comment by Jngai** [comment]
#1296
