### ISSUE TITLE
Event Creators should be able to copy old events

### ISSUE THREAD

**Issue by markottaviani** [ophrescue/RescueRails#997]
> I see that you added a Past Events Feature- which I use to go in and reuse a previous event. Would it be possible to have a duplicate event button? Where I can duplicate an event and then just change the date?

**Comment by lazylester** [comment]
Ah, I see. I think I disabled editing of past events... it seemed like editing history. But I can see why this would be useful.

**Comment by markottaviani** [comment]
I agree with the not being able to edit past events.

What if...

User views an old event, hits "copy/clone" and then have an `events/new` screen come up with everything pre-populated except for the date.

**Comment by lazylester** [comment]
perfect!
